from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Announcement", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=160)), ("body", models.TextField()), ("priority", models.CharField(choices=[("Routine", "Routine"), ("Important", "Important"), ("Urgent", "Urgent")], default="Routine", max_length=20)), ("published_at", models.DateTimeField(auto_now_add=True))], options={"ordering": ["-published_at"]}),
        migrations.CreateModel(name="Event", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=140)), ("description", models.TextField()), ("date", models.DateTimeField()), ("location", models.CharField(max_length=120)), ("category", models.CharField(default="MWR Activity", max_length=80))], options={"ordering": ["date"]}),
        migrations.CreateModel(name="Listing", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=140)), ("description", models.TextField()), ("price", models.DecimalField(decimal_places=2, max_digits=10)), ("category", models.CharField(choices=[("Vehicles", "Vehicles"), ("Electronics", "Electronics"), ("Furniture", "Furniture"), ("Outdoor Equipment", "Outdoor Equipment"), ("Services", "Services"), ("Miscellaneous", "Miscellaneous")], max_length=30)), ("condition", models.CharField(choices=[("New", "New"), ("Like New", "Like New"), ("Good", "Good"), ("Fair", "Fair")], max_length=20)), ("location", models.CharField(default="San Clemente Island", max_length=120)), ("image", models.ImageField(blank=True, upload_to="listings/")), ("is_sold", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("seller", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="listings", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="LostFound", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("kind", models.CharField(choices=[("Lost", "Lost"), ("Found", "Found")], max_length=10)), ("item", models.CharField(max_length=140)), ("description", models.TextField()), ("location", models.CharField(max_length=120)), ("date", models.DateField()), ("resolved", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="Profile", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("phone", models.CharField(blank=True, max_length=30)), ("department", models.CharField(blank=True, max_length=100)), ("bio", models.TextField(blank=True)), ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="SellerMessage", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("sender_name", models.CharField(max_length=100)), ("sender_email", models.EmailField(max_length=254)), ("message", models.TextField()), ("created_at", models.DateTimeField(auto_now_add=True)), ("listing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="community.listing"))]),
    ]
