# Generated by Django 5.2.16 on 2026-08-07 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_contentreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contentreport',
            name='unique_listing_report_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='contentreport',
            name='unique_lostfound_report_per_user',
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Free', 'Free Stuff'), ('For Sale', 'For Sale'), ('Volunteer Service', 'Volunteer Service'), ('Community Post', 'Community Post')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='contentreport',
            constraint=models.UniqueConstraint(condition=models.Q(('reporter__isnull', False)), fields=('reporter', 'listing'), name='unique_listing_report_per_user'),
        ),
        migrations.AddConstraint(
            model_name='contentreport',
            constraint=models.UniqueConstraint(condition=models.Q(('reporter__isnull', False)), fields=('reporter', 'lost_found'), name='unique_lostfound_report_per_user'),
        ),
    ]
