# Generated by Django 5.2.16 on 2026-08-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterestphotorequest',
            name='poi',
        ),
        migrations.RemoveField(
            model_name='pointofinterestphotorequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
        migrations.DeleteModel(
            name='PointOfInterestPhotoRequest',
        ),
    ]
