# Generated by Django 5.2.16 on 2026-09-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_remove_pointofinterestphotorequest_poi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, default='MWR Activity', max_length=80),
        ),
    ]
